---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hah3lga4knls/public_html/
    - /bin/cp -R classes $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R db $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R test $DEPLOYPATH
    - /bin/cp -R upload $DEPLOYPATH
    - /bin/cp -R view $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
